ALTER SESSION SET CONTAINER=FREEPDB1;
-- create the queue and queue table to support the chat
BEGIN
  DBMS_AQADM.CREATE_QUEUE_TABLE(
    QUEUE_TABLE        =>  'GAMEDB.GAME_CHAT_TABLE',
    QUEUE_PAYLOAD_TYPE =>  'JSON');

  DBMS_AQADM.CREATE_QUEUE(
    QUEUE_NAME         =>  'GAMEDB.GAME_CHAT_QUEUE',
    QUEUE_TABLE        =>  'GAMEDB.GAME_CHAT_TABLE');

  DBMS_AQADM.START_QUEUE(
    QUEUE_NAME         => 'GAMEDB.GAME_CHAT_QUEUE');
END;