version: "3.9"
services:
  # Oracle database container
  oracle:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports: 
      - '1521:1521'
    volumes:
      - oracledb:/opt/oracle/oradata
  # Node.js backend application container
  node:
    build: ./app/
    image: node-app
    container_name: node_app
    ports:
      - 3000:3000
    command: node index.js
    volumes:
      - ./app:/usr/app/
      - ./app/node_modules:/usr/app/node_modules
    networks:
      - demoNetwork
  # Nginx frontend container
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./flappy-bird:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - demoNetwork

networks:
  demoNetwork:
    name: demoNetwork
    driver: bridge

volumes:
  oracledb: