version: "3.9"
services:
  # Oracle database container
  oracle:
    image: container-registry.oracle.com/database/free:latest
    restart: unless-stopped
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=MySecurePassword123
    ports: 
      - '1521:1521'
    volumes:
      - oracledb:/opt/oracle/oradata
      - ./database-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 10s
    networks:
      - demoNetwork
  # Node.js backend application container
  node:
    build: ./app/
    image: node-app
    environment:
      - ORACLEDB_ADDRESS=oracle
      - ORACLEDB_PORT=1521
      - ORACLEDB_SERVICE=FREEPDB1
      - ORACLEDB_USER=GAMEDB
      - DB_PASSWORD=MySecurePassword123
      - SITEURL=localhost:3000
      - CHAT_POLL_INTERVAL=5000
      - CHAT_POLL_MESSAGE_COUNT=5
    restart: unless-stopped
    container_name: node_app
    ports:
      - 3000:3000
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - demoNetwork
  # Nginx frontend container
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - oracle
      - node
    volumes:
      - ./flappy-bird:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - demoNetwork

networks:
  demoNetwork:
    name: demoNetwork
    driver: bridge

volumes:
  oracledb: